:includedir: ./

== References

include::{includedir}/aap2_references.adoc[]

== Ansible navigator

This is the new wrapper which includes the old tools `ansible-playbook`, `ansible-config`, `ansible-inventory`.

`ansible-playbook -i inventory playbook.yml`

ansible-navigator run playbook.yml -i inventory -m stdout --> to get output in the same format as the previous ansible-playbook

=== Installing Automation Content Navigator



== Automation Controller and Hub Installation

0. Prerequisites

- Access without password to both machines
- If your system does not accomplish minimum requirements for RAM, you can disable this check using `-e ignore_preflight_errors=true` once you run the installer. 

1. Subscribe both systems

```
POOL_ID=$(subscription-manager list --all --available --matches="MCT3694" | grep Pool | awk '{ print $3}')
subscription-manager attach --pool=$POOL_ID
subscription-manager repos --enable ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms
```

2. Download the installer for both systems.

https://access.redhat.com/downloads/content/480

3. Install Private Automation Hub

Decompress the installer, and modify the inventory with the following information:

```
[automationcontroller]
# leave empty this part for the hub system

[automationhub]                        
hub.lab.net ansible_connection=local

[all:vars]
registry_url='xxxxx'
# The following values need to be created from https://access.redhat.com/terms-based-registry/#accounts
registry_username='xxxx|amarirom'
registry_password='xxx'

automationhub_admin_password='password'

automationhub_pg_host=''
automationhub_pg_port=''

automationhub_pg_database='automationhub'
automationhub_pg_username='automationhub'
automationhub_pg_password='password'
automationhub_pg_sslmode='prefer'


```

./setup.sh -e 'ignore_preflight_errors=true'





4. Install Controller

Same as the hub but with variables for controller


=== Working with Automation Hub

==== Playing with Execution Environments or Container Registry

Once you have automation hub available, you can download a tar image from it with the following isntructions:

```
podman login hub.lab.net
podman pull hub.lab.net/ee-29-rhel8:latest
```

To download a tar file from registry.redhat.io:

  1. podmain login registry.redhat.io
  2. podman search registry.redhat.io/ansible*
  3. podman pull registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8
  4. [root@workstation ~]# podman images
REPOSITORY                                                               TAG         IMAGE ID      CREATED     SIZE
registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8  latest      033242d8de80  7 days ago  361 MB
[root@workstation ~]# podman save -o ansible-builder-rhel8.tar 033242d8de80

  5. podman pull registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8
  6. Now, you are ready to check the image and save it as a tar file
  ```
podman images
podman save -o ansible-builder-rhel8.tar IMAGE_ID```


5. Integrate SSO with Private Automation Hub

First, remove all the information related to subscription manager:

`subscription-manager unregister ; subscription-manager clean ; yum clean all`

Change configuration from rhsm to point to RHSM, and comment baseurl:

```
# Server hostname:
hostname = subscription.rhsm.redhat.com 

# Server prefix:
prefix = /subscription

```

Register to cdn and provide the pool information:

```
POOL_ID=$(subscription-manager list --all --available --matches="MCT3694" | grep Pool | awk '{ print $3}')
subscription-manager attach --pool=$POOL_ID

```

Disable sslverify from all repos (this was causing a lot of headeaches):
`sed -i 's/sslverify = 1/sslverify = 0/g' /etc/yum.repos.d/redhat.repo`

Generate and Copy ssh key to hub.lab.example.com:



Edit the inventory file from the AAP2 installer:

[automationcontroller]
[automationcontroller:vars]
peers=execution_nodes
[execution_nodes]
[automationhub]
hub.lab.example.com asible_connection=ssh
[database]
[servicescatalog_workers]
[sso]
hub2.lab.example.com ansible_connection=local
[all:vars]
admin_password='redhat'
pg_host=''
pg_port=''
pg_database='awx'
pg_username='awx'
pg_password=''
pg_sslmode='prefer'  # set to 'verify-full' for client-side enforced SSL
registry_url='registry.redhat.io'
registry_username=''
registry_password=''
receptor_listener_port=27199
automationhub_admin_password=''
automationhub_pg_host=''
automationhub_pg_port=''
automationhub_pg_database='automationhub'
automationhub_pg_username='automationhub'
automationhub_pg_password='redhat'
automationhub_pg_sslmode='prefer'
sso_keystore_password=''
sso_console_admin_password=''

==== Playing with Collections

Check the video from Herve https://drive.google.com/drive/u/1/folders/1_K4umkP_5pnPbYIJkIjvUh50OjHnZmZa[Sync Collections], about how to sync Certified, Community and your own Collections.


