---
- name: Hello and hostname playbook to test
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World"
    - name: Hostname of machine 
      shell: hostname -f
      register: output
    - debug:
        msg: "This host is {{ output.stdout }}"
